services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - app-network
  project:
    build: .
    restart: on-failure
    container_name: project
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - .:/code
    networks:
      - app-network
    stdin_open: true
    tty: true

volumes:
  qdrant_data:
networks:
  app-network:
    driver: bridge
